### ISSUE TITLE
Error in Pip install 

### ISSUE THREAD

**Issue by aalok-sathe** [deepmind/hanabi-learning-environment#29]
When I try `pip install .`, I run into
```bash
'setuptools.build_meta' has no attribute '__legacy__'
```

Following some recommendations online, I also tried `pip install . --no-use-pep517`, however, to no avail.

Full installation error output:

```bash
Processing /home/aalok/code/hanabi/hanabi-learning-environment
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphjwdxubr
       cwd: /tmp/pip-req-build-6lvo9jzu
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/aalok/.local/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphjwdxubr Check the logs for full command output.
```

**Comment by QianqianF** [comment]
I run into a similar problem where I got `ImportError: No module named 'setuptools.build_meta'`. I'm running it in `virtualenv` and it got fixed by creating the `virtualenv` without `-system-site-packages` flag. You can check out this thread for a more detailed discussion. I think there is someone having the same issue without using `virtualenv`.
[https://github.com/pypa/pip/issues/6264](url)
